### ISSUE TITLE
[bug?] 特定网站打不开,dns错误

### ISSUE THREAD

**Issue by wen-long** [tuic-protocol/tuic#217]
https://howdns.works

浏览器白屏, tuic server 报错
<img width="574" alt="image" src="https://github.com/EAimTY/tuic/assets/4262398/c45d53b0-dae0-4bc1-bc05-d5648edcbd70">

tcpdump 能看到拿到了正确的 IP
<img width="333" alt="image" src="https://github.com/EAimTY/tuic/assets/4262398/6f5a2317-a899-480e-997f-43d54678ab79">

经测试切换其他 nameserver 后 tuic 依旧报同样错误
经测试其他代理软件始终正常

版本为 1.0.0 linux amd64

**Comment by wen-long** [comment]
补充 

gnu 的二进制没这个问题
怀疑是 rust musl 上游问题

我试着写几行代码用 rust 请求网址来最小复现
试下来不交叉编译的都没问题
交叉编译到 musl 总是报错,编译不成功

```
error: failed to run custom build command for `openssl-sys v0.9.90`

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/xx/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-111.26.0+1.1.1u/src/lib.rs:504:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

AND:

target/x86_64-unknown-linux-musl/release/build/openssl-sys-9eae9352b6fcfb76/out/openssl-build/build/src" && "make" "depend"


     0:     0x561a19bf465a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x561a19bf465a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x561a19bf465a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
     3:     0x561a19bf465a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
     4:     0x561a19c165de - core::fmt::write::h5a4baaff1bcd3eb5
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
     5:     0x561a19bf0fc5 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
     6:     0x561a19bf4425 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
     7:     0x561a19bf4425 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
     8:     0x561a19bf642f - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
     9:     0x561a19bf616b - std::panicking::default_hook::ha3500da57aa4ac4f
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
    10:     0x561a19bf69d8 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
    11:     0x561a19bf68d9 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
    12:     0x561a19bf4ac6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
    13:     0x561a19bf65e2 - rust_begin_unwind
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
    14:     0x561a19b3dd63 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
    15:     0x561a19b3e153 - core::result::unwrap_failed::hdff5465d74574b44
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
    16:     0x561a19b76854 - core::result::Result<T,E>::unwrap::h79bcd808c42076ff
    17:     0x561a19b74ead - openssl_src::Build::run_command::ha378f3a80f7bffd0
    18:     0x561a19b743f6 - openssl_src::Build::build::heaa9bdf8cb626b46
    19:     0x561a19b44496 - build_script_main::find_vendored::get_openssl::hb0fe808af84bf3c8
    20:     0x561a19b3fd78 - build_script_main::find_openssl::h8fe613b1e0808970
    21:     0x561a19b3fee1 - build_script_main::main::hdfe116f168d10add
    22:     0x561a19b438c3 - core::ops::function::FnOnce::call_once::ha4bdb259abca14ff
    23:     0x561a19b458f9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h96411edba287d462
    24:     0x561a19b437a9 - std::rt::lang_start::{{closure}}::h642c786401909ee4
    25:     0x561a19bec95c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
    26:     0x561a19bec95c - std::panicking::try::do_call::hce04e543bb1f4cbb
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    27:     0x561a19bec95c - std::panicking::try::h3342dd4e1f680968
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    28:     0x561a19bec95c - std::panic::catch_unwind::h148ce1e59ac0cee7
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    29:     0x561a19bec95c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
    30:     0x561a19bec95c - std::panicking::try::do_call::h7caaaeaf9401650b
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
    31:     0x561a19bec95c - std::panicking::try::he7d15285746cbbc2
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
    32:     0x561a19bec95c - std::panic::catch_unwind::h89fb4f50c0301fe0
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
    33:     0x561a19bec95c - std::rt::lang_start_internal::h078acd489417d3c1
                                 at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20

```

**Comment by gnattu** [comment]
musl的dns只要ipv6查询失败就会失败掉整个dns lookup，不会管ipv4是否成功，因此会和部分dns有非常严重的兼容性问题
